name=multiMotor
version=1.1.2
author=Mark Sheng <marksheng2020@gmail.com>
maintainer=Mark Sheng <marksheng2020@gmail.com>
sentence=A library that enables easy management of a motor attached to both channels of an l293d motor driver
paragraph=users are responsible for potential damage to their motor drivers, please read the wiki page on recommended hardware configurations
category=Communication
url=https://github.com/someone225/multiMotor
architectures=avr
includes=Arduino.h, multiMotor.h
depends=ArduinoHttpClient